name:                glacier-sync
version:             0.1.0.0
github:              "DaveCTurner/glacier-sync"
license:             BSD3
author:              "David Turner"
maintainer:          "dct25-1bsd191@mythic-beasts.com"
copyright:           "2018 David Turner"

description:         Please see the README on GitHub at <https://github.com/DaveCTurner/glacier-sync#readme>

dependencies:
- base >= 4.7 && < 5
- amazonka-glacier

library:
  source-dirs: src

executables:
  glacier-sync:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glacier-sync

tests:
  glacier-sync-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glacier-sync
    - hspec
