name:                glacier-sync
version:             0.1.0.0
github:              "DaveCTurner/glacier-sync"
license:             BSD3
author:              "David Turner"
maintainer:          "dct25-1bsd191@mythic-beasts.com"
copyright:           "2018 David Turner"

description:         Please see the README on GitHub at <https://github.com/DaveCTurner/glacier-sync#readme>

dependencies:
- base >= 4.7 && < 5
- amazonka
- amazonka-glacier
- amazonka-sts
- bytestring
- cryptonite
- conduit
- base16-bytestring
- text
- deepseq
- servant
- servant-server
- aeson
- wai
- warp
- stm
- http-client
- http-types
- http-client-tls
- lens
- mtl
- either
- timeout
- time
- iso8601-time
- async
- filepath

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror

executables:
  glacier-sync:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glacier-sync

tests:
  glacier-sync-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glacier-sync
    - hspec
